### ISSUE TITLE
Make it run with Rails 4

### ISSUE THREAD

**Issue by skalee** [riboseinc/synced_resources#12]
Or drop support, but from #1 I conclude that it's still required.

**Comment by ribose-jeffreylau** [comment]
@skalee That is correct, Rails 4 (4.1, 4.2+) is still required.

**Comment by skalee** [comment]
Actually, it still doesn't work for Rails 4.0. I'll fix it or drop support for that version.

**Comment by skalee** [comment]
Fixed with #27. A boilerplate code was incompatible, and it has been removed in that pull request.
