### ISSUE TITLE
Make it run with Rails 5

### ISSUE THREAD

**Issue by ribose-jeffreylau** [riboseinc/synced_resources#3]
e.g. [`ActionController.hide_action`](https://apidock.com/rails/ActionController/HideActions/ClassMethods/hide_action) is [no longer available](https://mensfeld.pl/2015/12/upgrading-to-ruby-on-rails-5-0-from-rails-4-2-application-use-case/).

**Comment by ribose-jeffreylau** [comment]
@skalee  What are your thoughts on this?

**Comment by ribose-jeffreylau** [comment]
Some related links on deprecation of `.hide_action`:
https://github.com/rails/rails/issues/18336
https://github.com/hashrocket/decent_exposure/pull/121

**Comment by skalee** [comment]
@ribose-jeffreylau Thanks! I'll make Travis builds passing first, then check out this one.

**Comment by skalee** [comment]
@ronaldtse @ribose-jeffreylau Do we need Rubinius support? I consider using refinement to provide a noop `#hide_action` implementation for modern Rails versions.

**Comment by ronaldtse** [comment]
@skalee don't think we need Rubinius for now. Thanks!

**Comment by skalee** [comment]
#21 resolves Rails 5.0 incompatibilities (failures described in #20 still apply though).

**Comment by skalee** [comment]
Fixed with #28.
